# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitgame < Formula
  desc "Gamify your GitHub productivity - compete with yourself or others"
  homepage "https://github.com/langtind/gitgame"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/gitgame/releases/download/v0.1.0/gitgame_0.1.0_darwin_amd64.tar.gz"
      sha256 "e6e244eddf540090a8f89ac7a80d7ab962fbeabb0e4284d56d0f9060272561e3"

      def install
        bin.install "gitgame"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/gitgame/releases/download/v0.1.0/gitgame_0.1.0_darwin_arm64.tar.gz"
      sha256 "4b793f3904fb1d59cdd4cd2967569f6cd82671f2f6b3f92d81d91430c45b9525"

      def install
        bin.install "gitgame"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gitgame/releases/download/v0.1.0/gitgame_0.1.0_linux_amd64.tar.gz"
      sha256 "8a63ec2fe1e073ddcdbe7dbabe2b391362bc328afa1884bf4537ae25c4b4473d"
      def install
        bin.install "gitgame"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gitgame/releases/download/v0.1.0/gitgame_0.1.0_linux_arm64.tar.gz"
      sha256 "64e190ae51c8efe9e1f42a1ebc558674fb73ee2cd0637cb02f6477ec94c2f397"
      def install
        bin.install "gitgame"
      end
    end
  end

  test do
    system "#{bin}/gitgame", "version"
  end
end
