# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gren < Formula
  desc "Git worktree manager with TUI and CLI"
  homepage "https://github.com/langtind/gren"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/gren/releases/download/v0.7.1/gren_0.7.1_darwin_amd64.tar.gz"
      sha256 "60cf78a6d0d15879aaf5bd08e34cd5711fd91fa36d7a9caf36b5b3d6bdd9dc33"

      def install
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/gren/releases/download/v0.7.1/gren_0.7.1_darwin_arm64.tar.gz"
      sha256 "686ed2117c1ac1770135c640a755379436ab3d578bcc8ac85aa9a4e4795a7e23"

      def install
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.7.1/gren_0.7.1_linux_amd64.tar.gz"
      sha256 "b8148ad88ba4a7fc622fdc5abe1a67dd226ea00204ad3a2655bf5e41c02d7311"
      def install
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.7.1/gren_0.7.1_linux_arm.tar.gz"
      sha256 "681e53393cc8dffc4c42571eef66ec0a6d2d12760e21e44507864d29b735cfed"
      def install
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.7.1/gren_0.7.1_linux_arm64.tar.gz"
      sha256 "950077bee1dd52b4fcae31403a882e25e3b87b4b7c352dca1636db30b609be90"
      def install
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
  end

  head "https://github.com/langtind/gren.git", branch: "main"

  head do
    depends_on "go" => :build
  end

  def caveats
    <<~EOS
      Navigation functionality requires shell integration.

      Add one of these lines to your shell config:

        # Zsh (~/.zshrc):
        eval "$(gren shell-init zsh)"

        # Bash (~/.bashrc):
        eval "$(gren shell-init bash)"

        # Fish (~/.config/fish/config.fish):
        gren shell-init fish | source

      This enables:
        - 'g' key in TUI to navigate to worktree folder
        - 'gcd <name>' alias for quick navigation
        - 'gren navigate <name>' command
    EOS
  end

  test do
    assert_match "gren version", shell_output("#{bin}/gren --version")
    assert_match "gren()", shell_output("#{bin}/gren shell-init zsh")
  end
end
