# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gren < Formula
  desc "Git worktree manager with TUI and CLI"
  homepage "https://github.com/langtind/gren"
  version "0.16.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/gren/releases/download/v0.16.2/gren_0.16.2_darwin_amd64.tar.gz"
      sha256 "6bef3871ca24a45dfb98efcf242c2252ae310c1153b48a97c23c1859fd28a686"

      define_method(:install) do
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/gren/releases/download/v0.16.2/gren_0.16.2_darwin_arm64.tar.gz"
      sha256 "b9c6d0f39c279ef935d381e76192ed1e81ae8d0d7292dd14d0799ea0e276254a"

      define_method(:install) do
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.16.2/gren_0.16.2_linux_amd64.tar.gz"
      sha256 "417abd559aa5b80dcfa242a2b5857d855cc9ce6c3f7b554a4f788aa8a61ad9ae"
      define_method(:install) do
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.16.2/gren_0.16.2_linux_arm.tar.gz"
      sha256 "e912d47aa5ae4d431c469c2c86c5f82e1b6c8ab412aa43f91028e1fe7c4e5122"
      define_method(:install) do
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/gren/releases/download/v0.16.2/gren_0.16.2_linux_arm64.tar.gz"
      sha256 "fb759ecfb857bc7345739ac211367909af8e1bd8eb20beed990f1dc6919e9b07"
      define_method(:install) do
        if build.head?
          ldflags = %W[
            -s -w
            -X main.version=HEAD-#{Utils.git_short_head}
            -X main.commit=#{Utils.git_short_head}
            -X main.date=#{time.iso8601}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install "gren"
        end
      end
    end
  end

  head "https://github.com/langtind/gren.git", branch: "main"

  head do
    depends_on "go" => :build
  end

  def caveats
    <<~EOS
      Navigation functionality requires shell integration.

      Add one of these lines to your shell config:

        # Zsh (~/.zshrc):
        eval "$(gren shell-init zsh)"

        # Bash (~/.bashrc):
        eval "$(gren shell-init bash)"

        # Fish (~/.config/fish/config.fish):
        gren shell-init fish | source

      This enables:
        - 'g' key in TUI to navigate to worktree folder
        - 'gcd <name>' alias for quick navigation
        - 'gren navigate <name>' command
    EOS
  end

  test do
    assert_match "gren version", shell_output("#{bin}/gren --version")
    assert_match "gren()", shell_output("#{bin}/gren shell-init zsh")
  end
end
