# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homeyctl < Formula
  desc "CLI for controlling Homey smart home"
  homepage "https://github.com/langtind/homeyctl"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/homeyctl/releases/download/v1.0.0/homeyctl_1.0.0_darwin_amd64.tar.gz"
      sha256 "a83fad1357c7d1d57db5130f5b071f0485563d2653eee92bf61a2da00313ce30"

      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/homeyctl/releases/download/v1.0.0/homeyctl_1.0.0_darwin_arm64.tar.gz"
      sha256 "a1021cc7a00b5e7b7db0cb5e9620b3f82f2c5b3a0c4d2b664051fcc60c8d9a8d"

      def install
        bin.install "homeyctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v1.0.0/homeyctl_1.0.0_linux_amd64.tar.gz"
      sha256 "ce7605c6aeaef9ee442935ee10227f6daf3d4bd1fa4ae99a71ed12334eda6ae9"
      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v1.0.0/homeyctl_1.0.0_linux_arm64.tar.gz"
      sha256 "44f3603abddae026695c44ecd0b8a40f7b9f0be00267946d2faaeb9d299bdf06"
      def install
        bin.install "homeyctl"
      end
    end
  end

  test do
    system "#{bin}/homeyctl", "version"
  end
end
