# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homeyctl < Formula
  desc "CLI for controlling Homey smart home"
  homepage "https://github.com/langtind/homeyctl"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/homeyctl/releases/download/v1.1.0/homeyctl_1.1.0_darwin_amd64.tar.gz"
      sha256 "f1f6bb58c35649240c911d700cd3f2f6996d87f0c682e4c11b66194ba30cf26f"

      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/homeyctl/releases/download/v1.1.0/homeyctl_1.1.0_darwin_arm64.tar.gz"
      sha256 "fa765fc390c5c2fb1ff6af2ddc9ea9c9bcd1acc0df45f9b54ba893010de8fb15"

      def install
        bin.install "homeyctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v1.1.0/homeyctl_1.1.0_linux_amd64.tar.gz"
      sha256 "f15616d3fb93ead60860a0d0b87496d420f0323cbed1057e53b4d5010f563600"
      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v1.1.0/homeyctl_1.1.0_linux_arm64.tar.gz"
      sha256 "8afff32a0c74bcb751c6978be73edbca96b20fb0a91d52b582bc5a3d817ac139"
      def install
        bin.install "homeyctl"
      end
    end
  end

  test do
    system "#{bin}/homeyctl", "version"
  end
end
