# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomeyCli < Formula
  desc "CLI for controlling Homey smart home"
  homepage "https://github.com/langtind/homey-cli"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/homey-cli/releases/download/v0.1.7/homey-cli_0.1.7_darwin_amd64.tar.gz"
      sha256 "cf56a0710669c8a5d5e6278ad453da9946ef32e97dd3d6a44605144eda920519"

      def install
        bin.install "homey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/homey-cli/releases/download/v0.1.7/homey-cli_0.1.7_darwin_arm64.tar.gz"
      sha256 "26f75b11c183a7a31c0913b89a51404fe0d518b922a8a74600acac28e3512a99"

      def install
        bin.install "homey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homey-cli/releases/download/v0.1.7/homey-cli_0.1.7_linux_amd64.tar.gz"
      sha256 "7a3b6dcfef705579a80e803f54a3c23f5a336d5f3650f279016fd44cde65a1ba"
      def install
        bin.install "homey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homey-cli/releases/download/v0.1.7/homey-cli_0.1.7_linux_arm64.tar.gz"
      sha256 "7229bcf0c05d43ba4dfdaec74895988542d4d8ea4fecc1fb1798eb8cb190a06d"
      def install
        bin.install "homey"
      end
    end
  end

  test do
    system "#{bin}/homey", "version"
  end
end
