# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Homeyctl < Formula
  desc "CLI for controlling Homey smart home"
  homepage "https://github.com/langtind/homeyctl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homeyctl_0.2.0_darwin_amd64.tar.gz"
      sha256 "f36e6f1d54bcdac228862e7be6c9200393eb8f2e053f74738630dc011803bdd4"

      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homeyctl_0.2.0_darwin_arm64.tar.gz"
      sha256 "9b9dd315b0ed7c8fb8a047c0f5aa07d163ee5f1994417847c26efa2ea35a89b2"

      def install
        bin.install "homeyctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homeyctl_0.2.0_linux_amd64.tar.gz"
      sha256 "148d8b5242028dd86f995c3fbaa76c77a2f30ad34cccf43838f342e8bb12bf6c"
      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homeyctl_0.2.0_linux_arm64.tar.gz"
      sha256 "e0e0ee94b75d74dd522f9df0b2024ae3f860cae4793d7ab84dbc06c757612cd0"
      def install
        bin.install "homeyctl"
      end
    end
  end

  test do
    system "#{bin}/homeyctl", "version"
  end
end
