# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomeyCli < Formula
  desc "CLI for controlling Homey smart home"
  homepage "https://github.com/langtind/homeyctl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homey-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "74621be32f7dbb07ab2810d97dcc9b8af618cec00ca079944230591d8242cc3b"

      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homey-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "f4d35cacf3b6b4d86f639e2d0edd6d54143c57b4ba313eb807293fa78d4b5404"

      def install
        bin.install "homeyctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homey-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "0e51b0421d10902099def62ea84dbaeab35691562ae4708684819b4bd549135b"
      def install
        bin.install "homeyctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/homeyctl/releases/download/v0.2.0/homey-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "9d603c77f7f96657ffb79ebff6ffaedc8fafcf2d5cb30e6ceb52b77363f19f54"
      def install
        bin.install "homeyctl"
      end
    end
  end

  test do
    system "#{bin}/homeyctl", "version"
  end
end
