# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynabctl < Formula
  desc "A CLI tool for interacting with the YNAB API"
  homepage "https://github.com/langtind/ynabctl"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.2/ynabctl_Darwin_x86_64.tar.gz"
      sha256 "569fda06f80796aea0854d74a54ce76b885380fbcb3d28d4df50505ce95b2d88"

      def install
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.2/ynabctl_Darwin_arm64.tar.gz"
      sha256 "7c88ff62ce97210a4fd8dc958d2a5461cfe06b298433cb64fe8d32770a81bb4a"

      def install
        bin.install "ynabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.2/ynabctl_Linux_x86_64.tar.gz"
      sha256 "4c3ca1a91e1d8f4502be8f54a4bf10d44f3113236dc687ba826233ef4ec04a54"
      def install
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.2/ynabctl_Linux_arm64.tar.gz"
      sha256 "13e5a8342b8fa65f7f5c3c2f059ddadb4f91836348a7c08ab2c4eea3cbdc4637"
      def install
        bin.install "ynabctl"
      end
    end
  end

  test do
    system "#{bin}/ynabctl", "version"
  end
end
