# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynabctl < Formula
  desc "A CLI tool for interacting with the YNAB API"
  homepage "https://github.com/langtind/ynabctl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.1/ynabctl_Darwin_x86_64.tar.gz"
      sha256 "78223ee9f45bd5af37c848af5b9de9b9b93e381b96392998942e2df4e0a08d0b"

      def install
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.1/ynabctl_Darwin_arm64.tar.gz"
      sha256 "66f0b7ac49618f7e6ef42ffe57d6e7f1f079f5a5fb9fa221bb000d6da97212bd"

      def install
        bin.install "ynabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.1/ynabctl_Linux_x86_64.tar.gz"
      sha256 "0f3887027bfc378a7d7c73a0022035c00d83fe9034a08ecef3cf0e38c8d4208c"
      def install
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.1.1/ynabctl_Linux_arm64.tar.gz"
      sha256 "54baafbd33dcf4fccf983292fa20c63edca1a12fec08818430aa2816e459aec9"
      def install
        bin.install "ynabctl"
      end
    end
  end

  test do
    system "#{bin}/ynabctl", "version"
  end
end
