# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynabctl < Formula
  desc "A CLI tool for interacting with the YNAB API"
  homepage "https://github.com/langtind/ynabctl"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langtind/ynabctl/releases/download/v0.2.1/ynabctl_Darwin_x86_64.tar.gz"
      sha256 "b967089d34fa980819f32e344556a6febe466ef2b9ead4e0e8e94ee81c7b4454"

      define_method(:install) do
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langtind/ynabctl/releases/download/v0.2.1/ynabctl_Darwin_arm64.tar.gz"
      sha256 "ec4175b6ed93b11050a3a03b2ba998b553231e4f11fce99f77043f9460eac4dc"

      define_method(:install) do
        bin.install "ynabctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.2.1/ynabctl_Linux_x86_64.tar.gz"
      sha256 "c12132b3eab6a6ddffbe49753ea40fd163f97ad4a7b5e18a80cc4b4e2ace123b"
      define_method(:install) do
        bin.install "ynabctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/langtind/ynabctl/releases/download/v0.2.1/ynabctl_Linux_arm64.tar.gz"
      sha256 "4f2611f1372c237f8d7e6004f2414b9225d8165871e3a100b28d47940522559c"
      define_method(:install) do
        bin.install "ynabctl"
      end
    end
  end

  test do
    system "#{bin}/ynabctl", "version"
  end
end
